name: kuzco_app
description: "A Project for catalog"
version: 1.0.0
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.9.1

  card_swiper: ^3.0.1
  shared_preferences: ^2.5.4
  collection: ^1.19.1
  intl: ^0.20.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

  # fonts:
  #   - family: mymIcons
  #     fonts:
  #       - asset: assets/icons/MYMIcons.ttf
  #   - family: Playfair
  #     fonts:
  #       - asset: assets/fonts/PlayfairDisplay-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/PlayfairDisplay-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/PlayfairDisplay-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/PlayfairDisplay-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/PlayfairDisplay-Black.ttf
  #         weight: 900

  #   - family: Playfair
  #     fonts:
  #       - asset: assets/fonts/PlayfairDisplay-Italic.ttf
  #         weight: 400
  #         style: italic
  #       - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic
  #       - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: assets/fonts/PlayfairDisplay-BlackItalic.ttf
  #         weight: 900
  #         style: italic
